locations = [
    { "ID": 1, "Name": "Temple of Ra", "Description": "A sunken temple full of puzzles and traps.", "Excavation Time (hours)": 6, "Used": False },
    { "ID": 2, "Name": "Tomb of unknown Pharaoh", "Description": "Ruins of a tomb buried deep in the sands.", "Excavation Time (hours)": 8, "Used": False },
    { "ID": 3, "Name": "Cursed Cavern", "Description": "A dark cave rumored to be haunted by spirits.", "Excavation Time (hours)": 5, "Used": False },
    { "ID": 4, "Name": "Crystal Grotto", "Description": "A shimmering cave filled with luminous crystals.", "Excavation Time (hours)": 4, "Used": False },
    { "ID": 5, "Name": "Old house", "Description": "An ancient structre, uninhabited for tousands of years...", "Excavation Time (hours)": 10, "Used": False },
    { "ID": 6, "Name": "Unknown Tomb", "Description": "Someone was buried here..", "Excavation Time (hours)": 7, "Used": False },
    { "ID": 7, "Name": "Trash site...", "Description": "Ancient used this spot to throw away things they didn't need anymore", "Excavation Time (hours)": 12, "Used": False },
    { "ID": 8, "Name": "Pharaoh's Tomb", "Description": "A lavish burial site filled with traps and treasures.", "Excavation Time (hours)": 9, "Used": False },
    { "ID": 9, "Name": "Giant's Causeway", "Description": "A massive rock formation with ancient runes carved into it.", "Excavation Time (hours)": 6, "Used": False },
    { "ID": 10, "Name": "Sunken Shipwreck", "Description": "The remains of a legendary ship lost to the... sand?!", "Excavation Time (hours)": 8, "Used": False },
    {"ID": 11, "Name": "Scarab Nest", "Description": "A hidden chamber filled with ancient scarab beetles.", "Excavation Time (hours)": 7, "Used": False},
    {"ID": 12, "Name": "Obsidian Obelisk", "Description": "A towering obelisk made of black obsidian, covered in hieroglyphs.", "Excavation Time (hours)": 5, "Used": False},
    {"ID": 13, "Name": "Anubis' Altar", "Description": "An altar dedicated to the god of the afterlife, Anubis.", "Excavation Time (hours)": 9, "Used": False},
    {"ID": 14, "Name": "Sun Temple", "Description": "A temple once used to worship Ra, the sun god.", "Excavation Time (hours)": 6, "Used": False},
    {"ID": 15, "Name": "Lighthouse of Thoth", "Description": "Ruins of an ancient lighthouse believed to guide souls to the afterlife.", "Excavation Time (hours)": 8, "Used": False},
    {"ID": 16, "Name": "Serpent's Pit", "Description": "A deep pit filled with the remnants of ancient serpents.", "Excavation Time (hours)": 4, "Used": False},
    {"ID": 17, "Name": "Temple of Sobek", "Description": "A temple dedicated to Sobek, the crocodile god.", "Excavation Time (hours)": 7, "Used": False},
    {"ID": 18, "Name": "Mirror Hall", "Description": "A mysterious hall filled with reflective surfaces.", "Excavation Time (hours)": 5, "Used": False},
    {"ID": 19, "Name": "Pharaoh's Garden", "Description": "An overgrown garden once filled with exotic plants.", "Excavation Time (hours)": 6, "Used": False},
    {"ID": 20, "Name": "Canyon of the Dead", "Description": "A canyon filled with the remains of long-forgotten warriors.", "Excavation Time (hours)": 9, "Used": False},
    {"ID": 21, "Name": "Statue of Horus", "Description": "A massive statue of the falcon-headed god Horus.", "Excavation Time (hours)": 4, "Used": False},
    {"ID": 22, "Name": "Isis' Shrine", "Description": "A shrine dedicated to Isis, goddess of magic and motherhood.", "Excavation Time (hours)": 7, "Used": False},
    {"ID": 23, "Name": "Library of Alexandria", "Description": "Remnants of ancient scrolls and books hidden in the desert.", "Excavation Time (hours)": 10, "Used": False},
    {"ID": 24, "Name": "Amun-Ra's Crypt", "Description": "A hidden crypt containing the remains of Amun-Ra's priests.", "Excavation Time (hours)": 8, "Used": False},
    {"ID": 25, "Name": "Pyramid of Shadows", "Description": "A pyramid shrouded in darkness, believed to be cursed.", "Excavation Time (hours)": 12, "Used": False},
    {"ID": 26, "Name": "Vulture's Nest", "Description": "An eerie cliffside where vultures once gathered.", "Excavation Time (hours)": 5, "Used": False},
    {"ID": 27, "Name": "Valley of the Kings", "Description": "A valley filled with the tombs of Egypt's greatest pharaohs.", "Excavation Time (hours)": 11, "Used": False},
    {"ID": 28, "Name": "River of the Underworld", "Description": "A dry riverbed once believed to connect to the afterlife.", "Excavation Time (hours)": 6, "Used": False},
    {"ID": 29, "Name": "Horus' Observatory", "Description": "An ancient observatory used to track celestial movements.", "Excavation Time (hours)": 9, "Used": False},
    {"ID": 30, "Name": "Sphinx's Secret", "Description": "A hidden chamber beneath the Great Sphinx.", "Excavation Time (hours)": 8, "Used": False},
    {"ID": 31, "Name": "Osiris' Throne Room", "Description": "A majestic throne room believed to be the seat of Osiris.", "Excavation Time (hours)": 7, "Used": False},
    {"ID": 32, "Name": "Labyrinth of Thoth", "Description": "A maze filled with traps and puzzles, guarding ancient knowledge.", "Excavation Time (hours)": 10, "Used": False},
    {"ID": 33, "Name": "Scarab King's Lair", "Description": "A lair filled with golden scarabs and hidden treasures.", "Excavation Time (hours)": 6, "Used": False},
    {"ID": 34, "Name": "Halls of Eternity", "Description": "A long corridor lined with carvings depicting the journey of souls.", "Excavation Time (hours)": 7, "Used": False},
    {"ID": 35, "Name": "Sandstorm Shrine", "Description": "A shrine said to control the powerful sandstorms of the desert.", "Excavation Time (hours)": 8, "Used": False},
    {"ID": 36, "Name": "Thoth's Library", "Description": "An ancient library containing the wisdom of Thoth.", "Excavation Time (hours)": 9, "Used": False},
    {"ID": 37, "Name": "Sunken Oasis", "Description": "A hidden oasis now buried beneath the sands.", "Excavation Time (hours)": 5, "Used": False},
    {"ID": 38, "Name": "Golden Pyramid", "Description": "A pyramid made entirely of gold, hidden from sight.", "Excavation Time (hours)": 12, "Used": False},
    {"ID": 39, "Name": "Cursed Labyrinth", "Description": "A maze filled with cursed traps and deadly creatures.", "Excavation Time (hours)": 10, "Used": False},
    {"ID": 40, "Name": "Viper's Nest", "Description": "A nest of vipers guarding an ancient artifact.", "Excavation Time (hours)": 7, "Used": False},
    {"ID": 41, "Name": "Obelisk of Osiris", "Description": "A towering obelisk inscribed with the secrets of Osiris.", "Excavation Time (hours)": 6, "Used": False},
    {"ID": 42, "Name": "Valley of the Forgotten", "Description": "A valley where the lost souls of ancient Egypt wander.", "Excavation Time (hours)": 9, "Used": False},
    {"ID": 43, "Name": "Ankh Chamber", "Description": "A hidden chamber containing the key to immortality.", "Excavation Time (hours)": 5, "Used": False},
    {"ID": 44, "Name": "Temple of Ma'at", "Description": "A temple dedicated to Ma'at, the goddess of truth and justice.", "Excavation Time (hours)": 8, "Used": False},
    {"ID": 45, "Name": "Hall of Mirrors", "Description": "A hall where illusions and reality blend together.", "Excavation Time (hours)": 7, "Used": False},
    {"ID": 46, "Name": "Tomb of the Sand King", "Description": "A tomb belonging to a forgotten pharaoh, ruler of the sands.", "Excavation Time (hours)": 11, "Used": False},
    {"ID": 47, "Name": "Cavern of the Winds", "Description": "A cavern where the winds of the desert howl eternally.", "Excavation Time (hours)": 5, "Used": False},
    {"ID": 48, "Name": "Shrine of Set", "Description": "A shrine dedicated to Set, the god of chaos and war.", "Excavation Time (hours)": 9, "Used": False},
    {"ID": 49, "Name": "Chamber of the Golden Scarab", "Description": "A chamber filled with golden scarabs and ancient artifacts.", "Excavation Time (hours)": 6, "Used": False},
    {"ID": 50, "Name": "Forgotten Necropolis", "Description": "A vast necropolis hidden beneath the sands.", "Excavation Time (hours)": 10, "Used": False},
    {"ID": 51, "Name": "Ruins of the Black Pyramid", "Description": "The remains of a pyramid shrouded in mystery and darkness.", "Excavation Time (hours)": 12, "Used": False},
    {"ID": 52, "Name": "Shadow Valley", "Description": "A valley where the sun never reaches, filled with ancient ruins.", "Excavation Time (hours)": 7, "Used": False},
    {"ID": 53, "Name": "Hall of the Golden Pharaoh", "Description": "A grand hall dedicated to a pharaoh whose wealth was unmatched.", "Excavation Time (hours)": 8, "Used": False},
    {"ID": 54, "Name": "Pyramid of the Moon", "Description": "A pyramid dedicated to the worship of the moon goddess.", "Excavation Time (hours)": 9, "Used": False},
    {"ID": 55, "Name": "Anubis' Lair", "Description": "A lair where the jackal-headed god Anubis is said to reside.", "Excavation Time (hours)": 7, "Used": False},
    {"ID": 56, "Name": "Pharaoh's Hidden Vault", "Description": "A secret vault filled with the treasures of a forgotten pharaoh.", "Excavation Time (hours)": 11, "Used": False},
    {"ID": 57, "Name": "Valley of the Serpents", "Description": "A treacherous valley inhabited by venomous serpents.", "Excavation Time (hours)": 5, "Used": False},
    {"ID": 58, "Name": "Temple of the Eternal Flame", "Description": "A temple where a flame has burned for thousands of years.", "Excavation Time (hours)": 8, "Used": False},
    {"ID": 59, "Name": "Crypt of the Lost Souls", "Description": "A crypt where the spirits of the damned are said to be trapped.", "Excavation Time (hours)": 9, "Used": False},
    {"ID": 60, "Name": "Labyrinth of the Lost", "Description": "A maze that is said to have no exit.", "Excavation Time (hours)": 10, "Used": False}
]